### PR TITLE
fix(elixir): Introduce question breaks after successful answers

### LINKED ISSUE #165: fix: Question break after successful answer
**Type**

Bug

**Current behaviour**

Right now the player synchronization works well as long as nobody answers correctly. There is no question break if the question was answered.

**Expected behaviour**

We need to introduce a question break after successful answers.

**Motivation / use case**

n/a

### PR DESCRIPTION
**Pull request by mrapacz**
**Summary**
This PR introduces changes mentioned in #165 

**Related issues**
closes: #165 

**Test plan**
You have to run `make start-dev`, answer correctly and watch the gameplay entering the _question_break_ state

### CODE REVIEW

**Review by mrapacz — COMMENTED** [review]
# NOTE
The changes in syntax not concerning the PR itself were introduced due to #127 running on-save.

File: aion/web/channels/room_channel.ex [hunk 1]
```diff
@@ -92,14 +93,9 @@ defmodule Aion.RoomChannel do
       Logger.info("[channel] Question timed out in room: #{room_id}. Fetching a new one...")
 
       case old_state do
-        :question -> send_question_break(socket)
-        :break -> send_display_question(socket)
+        :question -> become_in_question_break_state(socket)
+        :break -> become_in_question_displayed_state(socket)
```
Comment (pmrukot) [inline aion/web/channels/room_channel.ex]: `enter_question_break_state` and `enter_question_displayed_state`?

**Review by pmrukot — APPROVED** [review]

File: aion/web/channels/room_channel.ex (hunk 1 above)
Comment (mrapacz) [reply aion/web/channels/room_channel.ex]: Yeah, that sounds better, I took the `become` from Akka subconsciously :rofl:
