### PR TITLE
fix(elm): User-facing strings

### LINKED ISSUE #110: fix(elm): Fix typos, grammar, etc.
**Type**

Fix

**Current behaviour**

As for now the text we display is usually mediocre quality. Before presenting this app to other people, we should definitely do a cleanup.

### PR DESCRIPTION
**Pull request by mrapacz**
**Summary**
This PR's goal is to fix all the typos etc. that we have, so if you have any comments on how the strings should look, now is the time to post them.

**Related issues**
closes: #110 

**Test plan**
`make start-dev`

### CODE REVIEW

File: aion/web/elm/src/General/Constants.elm [hunk 1]
```diff
@@ -19,18 +19,18 @@ gameCardConfig location =
 panelCardConfig : Location -> SimpleCardConfig
 panelCardConfig location =
     { svgImage = (host location) ++ "svg/tasks.svg"
-    , title = "Panel"
-    , description = "Create new rooms, new categories and new questions."
+    , title = "Workspace"
+    , description = "Create new rooms, add new categories and new questions."
     , url = panelPath
-    , buttonText = "Visit panel"
+    , buttonText = "Visit workspace"
```
Comment (pmrukot) [inline aion/web/elm/src/General/Constants.elm:25]: All our resources in Elm code are put in a `/panel` directory and now we are changing this nomenclature in UX but not in the code.

**Review by pmrukot — APPROVED** [review]
Not sure about the change from `panel` -> `workspace` though. Sounds better but it would also require changes in code.

File: aion/web/elm/src/General/Constants.elm (hunk 1 above)
Comment (mrapacz) [reply aion/web/elm/src/General/Constants.elm:25]: Yes, I know. This is also why I'm not for introducing naming 'just for the dev process' because later it requires not only changes in UI, but also in the whole code. 

Anyway since you've given this feature a name 'panel', I think we could stick to using that in code and only switch the UI naming. We could also think about a terminal name for this feature and introduce it now everywhere - both in code and UI (but we may also do that after releasing v1, as we are mostly caring about releasing it asap now and will do the elm refactor later anyway).

Comment (pmrukot) [reply aion/web/elm/src/General/Constants.elm:25]: Let's merge this PR and we can address this in Elm refactor.

Comment (mrapacz) [reply aion/web/elm/src/General/Constants.elm:25]: Ack
